### ISSUE TITLE
P/B and Down Arrows Mixed Up

### ISSUE THREAD

**Issue by jgedmond** [rfrht/RFH-2#1]
The resistance values for the P/B and Down Arrow switches are reversed.  P/B is triggered by 16.9k Ohms and Down Arrow is triggered by 12k Ohms.  To fix this, I had to solder the 13k Ohm and 3.9k Ohm resistors in series and mount them in the "12k Ohm" holes below the P/B switch.  Secondly, I soldered a 12k Ohm resistor in the "13k Ohm" position below the Down Arrow switch and a short in the "3.9k Ohm" position to the right of the Down Arrow switch.

**Comment by rfrht** [comment]
Thank you **very much** for pointing it, @jgedmond ! Fixed, as per your report.

**Comment by jgedmond** [comment]
Thank you, enjoying the circuit.  I made top and bottom boards to make a "sandwich" for protection of the main board.  Waiting for 3/16" spacers to make sure those work.

73, Jim - N5JGE

**Comment by rfrht** [comment]
Ensure to send pictures!!!

**Comment by jgedmond** [comment]
I am out of town until later this week.  Parts from Digi-Key were delivered today, so I should put it together over the weekend and take pictures.
